In [0]:
# EDA packages
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction import DictVectorizer

In [2]:
from google.colab import files
files.upload()

Saving Book1.csv to Book1.csv


{'Book1.csv': b'name,sex\r\nMary,F\r\nAnna,F\r\nEmma,F\r\nElizabeth,F\r\nMinnie,F\r\nMargaret,F\r\nIda,F\r\nAlice,F\r\nBertha,F\r\nSarah,F\r\nAnnie,F\r\nClara,F\r\nElla,F\r\nFlorence,F\r\nCora,F\r\nMartha,F\r\nLaura,F\r\nNellie,F\r\nGrace,F\r\nCarrie,F\r\nMaude,F\r\nMabel,F\r\nBessie,F\r\nJennie,F\r\nGertrude,F\r\nJulia,F\r\nHattie,F\r\nEdith,F\r\nMattie,F\r\nRose,F\r\nCatherine,F\r\nLillian,F\r\nAda,F\r\nLillie,F\r\nHelen,F\r\nJessie,F\r\nLouise,F\r\nEthel,F\r\nLula,F\r\nMyrtle,F\r\nEva,F\r\nFrances,F\r\nLena,F\r\nLucy,F\r\nEdna,F\r\nMaggie,F\r\nPearl,F\r\nDaisy,F\r\nFannie,F\r\nJosephine,F\r\nDora,F\r\nRosa,F\r\nKatherine,F\r\nAgnes,F\r\nMarie,F\r\nNora,F\r\nMay,F\r\nMamie,F\r\nBlanche,F\r\nStella,F\r\nEllen,F\r\nNancy,F\r\nEffie,F\r\nSallie,F\r\nNettie,F\r\nDella,F\r\nLizzie,F\r\nFlora,F\r\nSusie,F\r\nMaud,F\r\nMae,F\r\nEtta,F\r\nHarriet,F\r\nSadie,F\r\nCaroline,F\r\nKatie,F\r\nLydia,F\r\nElsie,F\r\nKate,F\r\nSusan,F\r\nMollie,F\r\nAlma,F\r\nAddie,F\r\nGeorgia,F\r\nEliza,F\r\nLulu,F

In [0]:
df=pd.read_csv('Book1.csv')

In [4]:
df.head(10)

name sex
0       Mary   F
1       Anna   F
2       Emma   F
3  Elizabeth   F
4     Minnie   F
5   Margaret   F
6        Ida   F
7      Alice   F
8     Bertha   F
9      Sarah   F

In [5]:
df.dtypes

name    object
sex     object
dtype: object

In [6]:
df.isnull().isnull().sum()

name    0
sex     0
dtype: int64

In [0]:
df_names = df

In [0]:
# Replacing All F and M with 0 and 1 respectively
df_names.sex.replace({'F':0,'M':1},inplace=True)
df_names.sex.replace({'f':0,'m':1},inplace=True)

In [9]:
df_names.sex.unique()

array([0, 1])

In [10]:
df_names.dtypes

name    object
sex      int64
dtype: object

In [0]:
Xfeatures =df_names['name']

In [0]:
# Feature Extraction 
cv = CountVectorizer()
X = cv.fit_transform(Xfeatures)

In [13]:
cv.get_feature_names()

['aaban',
 'aabha',
 'aabid',
 'aabriella',
 'aachal',
 'aada',
 'aadam',
 'aadan',
 'aadarsh',
 'aaden',
 'aadesh',
 'aadhav',
 'aadhavan',
 'aadhi',
 'aadhira',
 'aadhvik',
 'aadhya',
 'aadhyan',
 'aadi',
 'aadian',
 'aadil',
 'aadin',
 'aadish',
 'aadison',
 'aadit',
 'aadith',
 'aadithya',
 'aaditri',
 'aaditya',
 'aadiv',
 'aadon',
 'aadrian',
 'aadrika',
 'aadrit',
 'aadvik',
 'aadvika',
 'aadya',
 'aadyn',
 'aaenab',
 'aafia',
 'aafreen',
 'aafrin',
 'aaftaab',
 'aaftab',
 'aagam',
 'aagand',
 'aage',
 'aagot',
 'aahaan',
 'aahan',
 'aahana',
 'aahil',
 'aahim',
 'aahir',
 'aahliyah',
 'aahna',
 'aahron',
 'aaidan',
 'aaiden',
 'aaidyn',
 'aaila',
 'aailiyah',
 'aailyah',
 'aaima',
 'aaira',
 'aairah',
 'aaisha',
 'aaishah',
 'aaiyana',
 'aaiza',
 'aaja',
 'aajad',
 'aajah',
 'aajaylah',
 'aajiv',
 'aajon',
 'aakanksha',
 'aakar',
 'aakarsh',
 'aakas',
 'aakash',
 'aakeem',
 'aakib',
 'aakilah',
 'aakira',
 'aakiyah',
 'aakriti',
 'aala',
 'aalaiya',
 'aalaiyah',
 'aalam',
 'aal

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
# Features 
X
# Labels
y = df_names.sex

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [17]:
# Naive Bayes Classifier
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X_train,y_train)
clf.score(X_test,y_test)


0.7005596336943092

In [18]:
# Accuracy of our Model
print("Accuracy of Model",clf.score(X_test,y_test)*100,"%")

Accuracy of Model 70.05596336943091 %


In [19]:
# Accuracy of our Model
print("Accuracy of Model",clf.score(X_train,y_train)*100,"%")

Accuracy of Model 99.00719544646373 %


### Sample Prediction

In [0]:
# Sample1 Prediction
sample_name = ["Mary"]
vect = cv.transform(sample_name).toarray()

In [21]:
vect

array([[0, 0, 0, ..., 0, 0, 0]])

In [22]:
# Female is 0, Male is 1
clf.predict(vect)

array([0])

In [0]:
# Sample2 Prediction
sample_name1 = ["Mark"]
vect1 = cv.transform(sample_name1).toarray()

In [24]:
clf.predict(vect1)

array([1])

In [0]:
# Sample3 Prediction of Russian Names
sample_name2 = ["Natasha"]
vect2 = cv.transform(sample_name2).toarray()

In [26]:
clf.predict(vect2)

array([0])

In [0]:
# Sample3 Prediction of Random Names
sample_name3 = ["Nefertiti","Nasha","Ama","Ayo","Xhavier","Ovetta","Tathiana","Xia","Joseph","Xianliang"]
vect3 = cv.transform(sample_name3).toarray()

In [28]:
clf.predict(vect3)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [0]:
# A function to do it
def genderpredictor(a):
    test_name = [a]
    vector = cv.transform(test_name).toarray()
    if clf.predict(vector) == 0:
        print("Female")
    else:
        print("Male")
    

In [30]:
genderpredictor("Martha")

Female


In [31]:
namelist = ["Yaa","Yaw","Femi","Masha"]
for i in namelist:
    print(genderpredictor(i))

Female
None
Female
None
Female
None
Female
None


### Using a custom function for feature analysis

In [0]:
# By Analogy most female names ends in 'A' or 'E' or has the sound of 'A'
def features(name):
    name = name.lower()
    return {
        'first-letter': name[0], # First letter
        'first2-letters': name[0:2], # First 2 letters
        'first3-letters': name[0:3], # First 3 letters
        'last-letter': name[-1],
        'last2-letters': name[-2:],
        'last3-letters': name[-3:],
    }

In [33]:
# Vectorize the features function
features = np.vectorize(features)
print(features(["Anna", "Hannah", "Peter","John","Vladmir","Mohammed"]))

[{'first-letter': 'a', 'first2-letters': 'an', 'first3-letters': 'ann', 'last-letter': 'a', 'last2-letters': 'na', 'last3-letters': 'nna'}
 {'first-letter': 'h', 'first2-letters': 'ha', 'first3-letters': 'han', 'last-letter': 'h', 'last2-letters': 'ah', 'last3-letters': 'nah'}
 {'first-letter': 'p', 'first2-letters': 'pe', 'first3-letters': 'pet', 'last-letter': 'r', 'last2-letters': 'er', 'last3-letters': 'ter'}
 {'first-letter': 'j', 'first2-letters': 'jo', 'first3-letters': 'joh', 'last-letter': 'n', 'last2-letters': 'hn', 'last3-letters': 'ohn'}
 {'first-letter': 'v', 'first2-letters': 'vl', 'first3-letters': 'vla', 'last-letter': 'r', 'last2-letters': 'ir', 'last3-letters': 'mir'}
 {'first-letter': 'm', 'first2-letters': 'mo', 'first3-letters': 'moh', 'last-letter': 'd', 'last2-letters': 'ed', 'last3-letters': 'med'}]


In [0]:
# Extract the features for the dataset
df_X = features(df_names['name'])

In [0]:
df_y = df_names['sex']

In [36]:
from sklearn.feature_extraction import DictVectorizer
 
corpus = features(["Mike", "Julia"])
dv = DictVectorizer()
dv.fit(corpus)
transformed = dv.transform(corpus)
print(transformed)
 

  (0, 1)	1.0
  (0, 3)	1.0
  (0, 5)	1.0
  (0, 7)	1.0
  (0, 9)	1.0
  (0, 10)	1.0
  (1, 0)	1.0
  (1, 2)	1.0
  (1, 4)	1.0
  (1, 6)	1.0
  (1, 8)	1.0
  (1, 11)	1.0


In [37]:
dv.get_feature_names()

['first-letter=j',
 'first-letter=m',
 'first2-letters=ju',
 'first2-letters=mi',
 'first3-letters=jul',
 'first3-letters=mik',
 'last-letter=a',
 'last-letter=e',
 'last2-letters=ia',
 'last2-letters=ke',
 'last3-letters=ike',
 'last3-letters=lia']

In [0]:
# Train Test Split
dfX_train, dfX_test, dfy_train, dfy_test = train_test_split(df_X, df_y, test_size=0.33, random_state=42)

In [39]:
dfX_train

array([{'first-letter': 'g', 'first2-letters': 'ga', 'first3-letters': 'gab', 'last-letter': 'h', 'last2-letters': 'ah', 'last3-letters': 'lah'},
       {'first-letter': 'k', 'first2-letters': 'ku', 'first3-letters': 'kus', 'last-letter': 'h', 'last2-letters': 'sh', 'last3-letters': 'ush'},
       {'first-letter': 'g', 'first2-letters': 'gi', 'first3-letters': 'gin', 'last-letter': 'n', 'last2-letters': 'in', 'last3-letters': 'gin'},
       ...,
       {'first-letter': 'e', 'first2-letters': 'el', 'first3-letters': 'elv', 'last-letter': 'a', 'last2-letters': 'na', 'last3-letters': 'ina'},
       {'first-letter': 'l', 'first2-letters': 'le', 'first3-letters': 'led', 'last-letter': 'r', 'last2-letters': 'er', 'last3-letters': 'ger'},
       {'first-letter': 'n', 'first2-letters': 'ne', 'first3-letters': 'nee', 'last-letter': 'u', 'last2-letters': 'tu', 'last3-letters': 'etu'}],
      dtype=object)

In [40]:

dv = DictVectorizer()
dv.fit_transform(dfX_train)


<83803x8593 sparse matrix of type '<class 'numpy.float64'>'
	with 502818 stored elements in Compressed Sparse Row format>

In [41]:
# Model building Using DecisionTree

from sklearn.tree import DecisionTreeClassifier
 
dclf = DecisionTreeClassifier()
my_xfeatures =dv.transform(dfX_train)
dclf.fit(my_xfeatures, dfy_train)


DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [0]:
# Build Features and Transform them
sample_name_eg = ["Alex"]
transform_dv =dv.transform(features(sample_name_eg))


In [0]:
vect3 = transform_dv.toarray()

In [44]:
# Predicting Gender of Name
# Male is 1,female = 0
dclf.predict(vect3)

array([1])

In [45]:
if dclf.predict(vect3) == 0:
    print("Female")
else:
    print("Male")

Male


In [46]:
# Second Prediction With Nigerian Name
name_eg1 = ["Chioma"]
transform_dv =dv.transform(features(name_eg1))
vect4 = transform_dv.toarray()
if dclf.predict(vect4) == 0:
    print("Female")
else:
    print("Male")

Female


In [0]:
# A function to do it
def genderpredictor1(a):
    test_name1 = [a]
    transform_dv =dv.transform(features(test_name1))
    vector = transform_dv.toarray()
    if dclf.predict(vector) == 0:
        print("Female")
    else:
        print("Male")
    

In [0]:
random_name_list = ["Alex","Alice","Chioma","Vitalic","Clairese","Chan"]

In [49]:
for n in random_name_list:
    print(genderpredictor1(n))

Male
None
Female
None
Female
None
Male
None
Female
None
Male
None


In [50]:
## Accuracy of Models Decision Tree Classifier Works better than Naive Bayes
# Accuracy on training set
print(dclf.score(dv.transform(dfX_train), dfy_train)) 
 

0.9807286135341217


In [51]:
# Accuracy on test set
print(dclf.score(dv.transform(dfX_test), dfy_test))

0.8785764469317053


### Saving Our Model

In [0]:
from sklearn.externals import joblib

In [0]:
decisiontreModel = open("decisiontreemodel.pkl","wb")

In [0]:
joblib.dump(dclf,decisiontreModel)

In [55]:
decisiontreModel.close

<function BufferedWriter.close>

In [0]:
#Alternative to Model Saving
import pickle
dctreeModel = open("namesdetectormodel.pkl","wb")

In [0]:
pickle.dump(dclf,dctreeModel)

In [0]:
dctreeModel.close()

##### Save Multinomial NB Model

In [0]:
NaiveBayesModel = open("naivebayesgendermodel.pkl","wb")

In [0]:
joblib.dump(clf,NaiveBayesModel)

In [0]:
NaiveBayesModel.close()

In [0]:
from google.colab import files
files.download('naivebayesgendermodel.pkl')

In [0]:
from google.colab import files
files.download('decisiontreemodel.pkl')